server:
  port: 8081
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: Zjh990713_mysql
    url: jdbc:mysql://localhost:3306/Fitness_foods?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root