server:
  port: 8081
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: Zjh990713_mysql
    url: jdbc:mysql://localhost:3306/Fitness?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
  kafka:
    #kafka服务器地址可以多个
    bootstrap-servers: localhost:9092
    producer:
      #每次批量发送消息的数量
      batch-size: 65536
      #缓存大小
      buffer-memory: 524288
      #key-value的序列化
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      #指定一个默认的组名
      group-id: test
      #key-value的反序列化
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
user:
  redisLoginTableName: loginUserList #已登陆用户记录集合名
  tokenTotal: 5      #每个用户最多拥有token数量
  tokenTimeOut: 600s #token超时时间｜s秒 ms毫秒
  tokenSpaceMark: -- #token信息间隔符
  scheduleStartCleanTokenTime: 0s #项目启动后开始清理token时间｜s秒 ms毫秒
  scheduleCleanTokenTime: 120s #清理token间隔时间｜s秒 ms毫秒
  secret: Zjh990713_fitnessProject #token密钥

redis:
  ip: 127.0.0.1
  port: 6379
  maxTotal: 10
  maxIdle: 10
  waitMill: 0
  password: Zjh990713_redis
mongodb:
  ip: 127.0.0.1
  connectionsPerHost: 50
  threadsAllowedToBlockForConnectionMultiplier: 50
  maxWaitTime: 120s
  connectTimeout: 60s
  gridFS:
    databaseName: storageTank
    cllectionName: fs
